const cars = [{
        image: "./images/car1.png",
        name: "Mercedes Benz GLA",
        type: "SUV",
        category: "Standard",
        persons: 5,
        suitcases: 4,
        price: 900,
    },
    {
        image: "./images/car2.png",
        name: "Audi A3",
        type: "Hatchback",
        category: "Standard",
        persons: 5,
        suitcases: 3,
        price: 700,
    },
    {
        image: "./images/car3.png",
        name: "BMW i8",
        type: "Sport",
        category: "Standard",
        persons: 4,
        suitcases: 3,
        price: 1400,
    },
    {
        image: "./images/car4.png",
        name: "Mercedes Benz Vito",
        type: "Van",
        category: "Van",
        persons: 9,
        suitcases: 6,
        price: 1300,
    },
    {
        image: "./images/car5.png",
        name: "Audi Q7",
        type: "SUV",
        category: "Limousine",
        persons: 7,
        suitcases: 5,
        price: 2000,
    },
];